-- 자동 생성 파일 — 수정하지 마세요. src/data/questions.ts 를 고친 뒤
-- `npx tsx scripts/gen-seed.ts` 로 다시 생성하세요.
insert into public.questions
  (id, subject, category, difficulty, stem, choices, answer_index, explanation, sql_steps, tags)
values
  ('q001', 'data_modeling', 'modeling_basics', 1, '데이터 모델링의 3가지 관점(구성요소)에 해당하지 않는 것은?', '["데이터(Entity/Attribute)","프로세스(Process)","데이터와 프로세스의 관계(CRUD)","물리적 저장장치(Storage)"]'::jsonb, 3, '데이터 모델링의 3요소는 ① 데이터(무엇), ② 프로세스(어떻게), ③ 데이터와 프로세스의 상관관계(CRUD 매트릭스)이다. 물리적 저장장치는 모델링 관점이 아니다.', null::jsonb, '["모델링개요","CRUD"]'::jsonb),
  ('q002', 'data_modeling', 'modeling_basics', 2, '다음 중 식별자(Identifier)에 대한 설명으로 옳지 않은 것은?', '["주식별자는 유일성과 최소성을 만족해야 한다.","주식별자는 값이 자주 변경되어도 무방하다.","본질식별자는 업무에 의해 만들어지는 식별자다.","인조식별자는 자연스러운 식별자가 없을 때 인위적으로 부여한다."]'::jsonb, 1, '주식별자의 4대 특징은 유일성·최소성·불변성·존재성이다. 값이 자주 변경되면 불변성에 위배되므로 주식별자로 부적합하다.', null::jsonb, '["식별자","주식별자"]'::jsonb),
  ('q003', 'data_modeling', 'modeling_basics', 2, '정규화에 대한 설명으로 가장 적절한 것은?', '["제1정규형은 부분 함수 종속을 제거한 상태다.","제2정규형은 이행 함수 종속을 제거한 상태다.","제3정규형은 기본키가 아닌 속성 간의 종속(이행 종속)을 제거한 상태다.","정규화를 하면 항상 조회 성능이 향상된다."]'::jsonb, 2, '1NF=속성 원자성, 2NF=부분함수종속 제거, 3NF=이행함수종속 제거. 정규화는 중복을 줄여 저장·정합성에 유리하나, 조인이 늘어 조회 성능은 오히려 나빠질 수 있다.', null::jsonb, '["정규화","함수종속"]'::jsonb),
  ('q004', 'data_modeling', 'modeling_performance', 2, '반정규화(De-normalization)를 고려해야 하는 상황으로 가장 거리가 먼 것은?', '["정규화에 충실했으나 조인이 많아 조회 성능이 심각하게 저하된 경우","대량 범위 처리를 자주 수행해 처리 성능이 느린 경우","특정 통계 계산이 빈번해 매번 집계 비용이 큰 경우","데이터 정합성을 최우선으로 보장해야 하는 경우"]'::jsonb, 3, '반정규화는 조회 성능을 위해 중복을 허용하는 기법으로 정합성 관리 부담이 커진다. 정합성이 최우선이면 반정규화 대상이 아니다.', null::jsonb, '["반정규화","성능"]'::jsonb),
  ('q005', 'data_modeling', 'modeling_performance', 3, '슈퍼타입/서브타입 모델을 물리 테이블로 변환하는 방식 중, 서브타입이 많고 각 서브타입 속성이 매우 다를 때 유리한 방식은?', '["One To One Type (서브타입별 개별 테이블)","Plus Type (슈퍼+서브 분리)","Single Type / All in One (하나의 테이블로 통합)","슈퍼타입 제거 방식"]'::jsonb, 0, '서브타입이 많고 속성이 크게 다르면 One To One(서브타입별 테이블 분리)이 유리하다. 반대로 서브타입이 적고 트랜잭션이 통합적이면 All in One이 유리하다.', null::jsonb, '["슈퍼타입","서브타입","물리모델"]'::jsonb),
  ('q006', 'data_modeling', 'modeling_performance', 2, '관계형 DB에서 NULL에 대한 설명으로 옳은 것은?', '["NULL은 공백(space) 또는 0과 같다.","COUNT(*)는 NULL이 포함된 행을 제외하고 센다.","NULL과의 산술 연산 결과는 NULL이다.","NULL은 인덱스에 항상 저장된다."]'::jsonb, 2, 'NULL은 ''알 수 없음''이며 0/공백과 다르다. NULL과의 산술 연산·비교 결과는 NULL(UNKNOWN)이다. COUNT(*)는 행 수를 세므로 NULL 행도 포함, COUNT(칼럼)은 NULL 제외.', null::jsonb, '["NULL"]'::jsonb),
  ('q007', 'sql', 'sql_basics', 1, 'SQL 문장의 논리적 실행(처리) 순서를 올바르게 나열한 것은?', '["SELECT → FROM → WHERE → GROUP BY → HAVING → ORDER BY","FROM → WHERE → GROUP BY → HAVING → SELECT → ORDER BY","FROM → GROUP BY → WHERE → HAVING → SELECT → ORDER BY","WHERE → FROM → GROUP BY → SELECT → HAVING → ORDER BY"]'::jsonb, 1, '논리적 실행 순서: FROM/JOIN → WHERE → GROUP BY → HAVING → SELECT → ORDER BY. 작성 순서(SELECT 먼저)와 다르다는 점이 핵심.', null::jsonb, '["실행순서"]'::jsonb),
  ('q008', 'sql', 'sql_basics', 2, 'NULL 처리 함수에 대한 설명으로 옳지 않은 것은?', '["NVL(expr1, expr2)는 expr1이 NULL이면 expr2를 반환한다.","NULLIF(a, b)는 a=b이면 NULL, 아니면 a를 반환한다.","COALESCE는 인자 중 첫 번째 NOT NULL 값을 반환한다.","NVL2(expr1, a, b)는 expr1이 NULL이면 a를 반환한다."]'::jsonb, 3, 'NVL2(expr1, a, b)는 expr1이 NOT NULL이면 a, NULL이면 b를 반환한다. 보기 설명은 반대로 되어 있다.', null::jsonb, '["NULL함수","NVL","COALESCE"]'::jsonb),
  ('q009', 'sql', 'sql_basics', 2, 'WHERE 절에서 sal 컬럼에 NULL이 들어 있는 행을 조회하려 한다. 올바른 조건은?', '["WHERE sal = NULL","WHERE sal != NULL","WHERE sal IS NULL","WHERE sal <> ''''"]'::jsonb, 2, 'NULL은 =/!= 로 비교할 수 없다(결과가 UNKNOWN). 반드시 IS NULL / IS NOT NULL 을 사용한다.', null::jsonb, '["NULL","WHERE"]'::jsonb),
  ('q010', 'sql', 'sql_basics', 2, '다음 쿼리의 단계별 결과를 참고할 때 최종 출력 행 수는? (아래 ''단계별 결과'' 참고)', '["1행","2행","3행","4행"]'::jsonb, 1, 'WHERE sal>=250 으로 3행이 남고, GROUP BY dept 로 부서별 그룹, HAVING COUNT(*)>=2 로 인원 2명 이상 부서만 남긴다. 최종 2개 부서(SALES, DEV) → 2행.', '{"query":"SELECT dept, COUNT(*) AS cnt FROM emp WHERE sal >= 250 GROUP BY dept HAVING COUNT(*) >= 2 ORDER BY cnt DESC","steps":[{"clause":"FROM / JOIN","desc":"emp 테이블 전체를 읽는다.","table":{"columns":["name","dept","sal"],"data":[["Kim","SALES",300],["Lee","SALES",250],["Park","DEV",400],["Choi","DEV",260],["Yun","HR",220],["Han","DEV",240]]}},{"clause":"WHERE","desc":"sal >= 250 인 행만 남긴다. (Yun 220, Han 240 제거)","table":{"columns":["name","dept","sal"],"data":[["Kim","SALES",300],["Lee","SALES",250],["Park","DEV",400],["Choi","DEV",260]]}},{"clause":"GROUP BY","desc":"dept 기준으로 그룹핑한다.","table":{"columns":["dept","members"],"data":[["SALES","Kim, Lee"],["DEV","Park, Choi"]]}},{"clause":"HAVING","desc":"COUNT(*) >= 2 인 그룹만 남긴다. (둘 다 2명이라 유지)","table":{"columns":["dept","cnt"],"data":[["SALES",2],["DEV",2]]}},{"clause":"SELECT","desc":"dept, COUNT(*) AS cnt 를 출력한다.","table":{"columns":["dept","cnt"],"data":[["SALES",2],["DEV",2]]}},{"clause":"ORDER BY","desc":"cnt 내림차순 정렬 (동률이라 순서 유지).","table":{"columns":["dept","cnt"],"data":[["SALES",2],["DEV",2]]}}]}'::jsonb, '["GROUP BY","HAVING","실행순서"]'::jsonb),
  ('q011', 'sql', 'sql_basics', 1, '다음 중 집계 함수(Aggregate Function)와 그룹 처리에 대한 설명으로 옳은 것은?', '["WHERE 절에서 집계함수 조건을 사용할 수 있다.","GROUP BY 에 없는 일반 컬럼도 SELECT 절에 자유롭게 쓸 수 있다.","HAVING 절은 그룹핑 후의 집계 결과에 조건을 건다.","COUNT(칼럼)은 NULL도 포함하여 센다."]'::jsonb, 2, '집계 조건은 HAVING(그룹 후)에서 건다. GROUP BY 미포함 일반컬럼은 SELECT에 못 쓴다. COUNT(칼럼)은 NULL 제외, COUNT(*)만 전체 행을 센다.', null::jsonb, '["집계함수","HAVING","GROUP BY"]'::jsonb),
  ('q012', 'sql', 'sql_advanced', 2, '다음 조인 결과를 참고할 때, INNER JOIN 결과 행 수는? (단계별 결과 참고)', '["2행","3행","4행","5행"]'::jsonb, 1, 'dept.id 와 emp.dept_id 가 일치하는 행만 결합된다. HR(30)에 속한 사원이 없고, dept_id가 NULL/미매칭인 사원은 제외되어 3행이 남는다.', '{"query":"SELECT e.name, d.dname FROM emp e INNER JOIN dept d ON e.dept_id = d.id","steps":[{"clause":"FROM / JOIN","desc":"emp(왼쪽), dept(오른쪽) 두 테이블을 준비한다.","table":{"columns":["emp.name","emp.dept_id","dept.id","dept.dname"],"data":[["Kim",10,10,"SALES"],["Lee",20,20,"DEV"],["Park",20,30,"HR"],["Choi",null,"-","-"]]}},{"clause":"ON (JOIN 조건)","desc":"e.dept_id = d.id 로 매칭되는 조합만 남긴다. Choi(NULL)와 HR(30)은 짝이 없어 탈락.","table":{"columns":["name","dept_id","dname"],"data":[["Kim",10,"SALES"],["Lee",20,"DEV"],["Park",20,"DEV"]]}},{"clause":"SELECT","desc":"e.name, d.dname 출력 → 3행.","table":{"columns":["name","dname"],"data":[["Kim","SALES"],["Lee","DEV"],["Park","DEV"]]}}]}'::jsonb, '["JOIN","INNER JOIN"]'::jsonb),
  ('q013', 'sql', 'sql_advanced', 3, '다음 중 OUTER JOIN에 대한 설명으로 옳지 않은 것은?', '["LEFT OUTER JOIN은 왼쪽 테이블의 모든 행을 보존한다.","매칭되지 않는 쪽의 컬럼은 NULL로 채워진다.","FULL OUTER JOIN은 양쪽의 매칭 안 되는 행을 모두 보존한다.","OUTER JOIN 결과 행 수는 항상 INNER JOIN보다 적다."]'::jsonb, 3, 'OUTER JOIN은 매칭 안 되는 행까지 보존하므로 결과 행 수가 INNER JOIN보다 크거나 같다. ''항상 적다''는 틀린 설명.', null::jsonb, '["OUTER JOIN"]'::jsonb),
  ('q014', 'sql', 'sql_advanced', 3, '윈도우 함수 ROW_NUMBER(), RANK(), DENSE_RANK()에 대한 설명으로 옳은 것은?', '["값이 동일하면 세 함수 모두 같은 번호를 부여한다.","RANK()는 동순위 뒤 순위를 건너뛰고, DENSE_RANK()는 건너뛰지 않는다.","ROW_NUMBER()는 동순위에 같은 번호를 준다.","DENSE_RANK()는 동순위 뒤 순위를 건너뛴다."]'::jsonb, 1, '동일 값(예: 100,100,90)에서 RANK는 1,1,3(건너뜀), DENSE_RANK는 1,1,2(안 건너뜀), ROW_NUMBER는 1,2,3(무조건 유일 번호).', null::jsonb, '["윈도우함수","RANK","ROW_NUMBER"]'::jsonb),
  ('q015', 'sql', 'sql_advanced', 2, '집합 연산자에 대한 설명으로 옳지 않은 것은?', '["UNION은 중복을 제거하고 정렬 부하가 있을 수 있다.","UNION ALL은 중복을 제거하지 않고 그대로 합친다.","INTERSECT는 두 집합의 교집합을 반환한다.","MINUS(EXCEPT)는 두 집합의 합집합을 반환한다."]'::jsonb, 3, 'MINUS(EXCEPT)는 첫 집합에서 두 번째 집합을 뺀 ''차집합''을 반환한다. 합집합은 UNION이다.', null::jsonb, '["집합연산","UNION","MINUS"]'::jsonb),
  ('q016', 'sql', 'sql_advanced', 3, '다음 계층형 질의(CONNECT BY)에서 START WITH 와 CONNECT BY PRIOR의 역할로 옳은 것은?', '["START WITH는 전개 방향을, CONNECT BY는 루트 행을 지정한다.","START WITH는 루트(시작) 행을, CONNECT BY PRIOR는 부모-자식 전개 규칙을 지정한다.","둘 다 정렬을 담당한다.","CONNECT BY는 중복 제거를 담당한다."]'::jsonb, 1, 'START WITH = 계층 전개의 루트 행 지정, CONNECT BY PRIOR = 부모-자식 관계(전개 규칙) 지정. LEVEL 의사컬럼으로 깊이를 알 수 있다.', null::jsonb, '["계층형질의","CONNECT BY"]'::jsonb),
  ('q017', 'sql', 'sql_advanced', 2, '스칼라 서브쿼리(Scalar Subquery)에 대한 설명으로 옳은 것은?', '["SELECT 절에 위치하며 한 행·한 컬럼(단일 값)을 반환해야 한다.","여러 행을 반환해도 오류가 나지 않는다.","FROM 절에서만 사용할 수 있다.","메인쿼리 컬럼을 참조할 수 없다."]'::jsonb, 0, '스칼라 서브쿼리는 SELECT 절 등에서 단일 값(1행 1컬럼)을 반환해야 하며, 2행 이상 반환 시 오류. 메인쿼리 컬럼 참조(상관 서브쿼리) 가능.', null::jsonb, '["서브쿼리","스칼라서브쿼리"]'::jsonb),
  ('q018', 'sql', 'sql_management', 2, 'DDL/DML/TCL 분류로 옳은 것은?', '["TRUNCATE는 DML이며 ROLLBACK으로 복구할 수 있다.","TRUNCATE는 DDL이며 자동 커밋되어 ROLLBACK이 불가하다.","DELETE는 DDL이다.","COMMIT은 DDL이다."]'::jsonb, 1, 'TRUNCATE는 DDL로 즉시 자동 커밋되어 ROLLBACK 불가하며 저장공간을 반납한다. DELETE는 DML이라 ROLLBACK 가능. COMMIT/ROLLBACK은 TCL.', null::jsonb, '["DDL","TRUNCATE","DELETE"]'::jsonb),
  ('q019', 'sql', 'sql_management', 2, '제약조건(Constraint)에 대한 설명으로 옳지 않은 것은?', '["PRIMARY KEY는 UNIQUE + NOT NULL 성질을 가진다.","FOREIGN KEY는 참조 무결성을 보장한다.","UNIQUE 제약이 걸린 컬럼에는 NULL을 절대 넣을 수 없다.","CHECK 제약은 컬럼 값의 범위·조건을 제한한다."]'::jsonb, 2, 'UNIQUE는 중복만 막을 뿐 NULL은 (일반적으로 여러 개) 허용된다. NOT NULL을 함께 걸어야 NULL을 막는다.', null::jsonb, '["제약조건","UNIQUE","PK"]'::jsonb),
  ('q020', 'sql', 'sql_management', 3, '권한 관리 명령에 대한 설명으로 옳은 것은?', '["GRANT는 권한을 회수하는 명령이다.","REVOKE는 권한을 부여하는 명령이다.","ROLE은 여러 권한을 묶어 관리하는 객체다.","WITH GRANT OPTION은 권한을 절대 재부여하지 못하게 한다."]'::jsonb, 2, 'GRANT=부여, REVOKE=회수, ROLE=권한 묶음. WITH GRANT OPTION은 부여받은 사용자가 다시 다른 사용자에게 권한을 줄 수 있게 한다.', null::jsonb, '["권한","GRANT","ROLE"]'::jsonb)
on conflict (id) do update set
  subject = excluded.subject,
  category = excluded.category,
  difficulty = excluded.difficulty,
  stem = excluded.stem,
  choices = excluded.choices,
  answer_index = excluded.answer_index,
  explanation = excluded.explanation,
  sql_steps = excluded.sql_steps,
  tags = excluded.tags;
