'use client';
import { useEffect, useMemo, useState } from 'react';
import { questions, type Confidence } from '@/lib/questions';
const labels: Record<Confidence,string>={확실함:'확실해요',애매함:'애매해요',찍음:'찍었어요'};
export default function CoachApp(){
 const [index,setIndex]=useState(0),[picked,setPicked]=useState<number|undefined>(),[confidence,setConfidence]=useState<Confidence>('애매함'),[answered,setAnswered]=useState(false),[tab,setTab]=useState<'today'|'review'|'stats'>('today'),[history,setHistory]=useState<Record<number,boolean>>({}),[showStages,setShowStages]=useState(false);
 const q=questions[index]; const completed=Object.keys(history).length; const wrong=Object.entries(history).filter(([,v])=>!v).length;
 useEffect(()=>{ if('serviceWorker' in navigator) navigator.serviceWorker.register('/sw.js'); },[]);
 const score=useMemo(()=>Math.round(52 + Math.min(completed,6)*1.5),[completed]);
 function next(){ if(!answered) return; setHistory(h=>({...h,[q.id]:picked===q.answer})); if(index<questions.length-1){setIndex(index+1);setPicked(undefined);setAnswered(false);setShowStages(false)} }
 return <main className="mx-auto min-h-screen max-w-md bg-cream pb-24 text-ink">
  <header className="px-5 pt-7"><div className="flex items-center justify-between"><div><p className="text-xs font-bold tracking-[.18em] text-teal-700">SQLD 30일 코치</p><h1 className="mt-1 text-2xl font-black">오늘, 2문제 더 맞히기</h1></div><div className="rounded-2xl bg-navy px-3 py-2 text-center text-white"><b className="text-lg">D-30</b><span className="block text-[10px] opacity-70">시험까지</span></div></div>
  <div className="mt-5 rounded-3xl bg-navy p-5 text-white shadow-card"><div className="flex justify-between text-sm"><span className="font-bold">오늘의 집중 루틴</span><span className="text-mint">{completed}/20 완료</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-white/20"><div className="h-full rounded-full bg-mint" style={{width:`${completed/20*100}%`}}/></div><p className="mt-3 text-xs text-white/70">출퇴근 20분 · SQL 기본 및 활용 중심</p></div></header>
  <section className="px-5 pt-5">{tab==='today'&&<><div className="mb-3 flex items-center justify-between"><h2 className="font-black">오늘의 문제</h2><span className="rounded-full bg-orange-100 px-3 py-1 text-xs font-bold text-orange-600">{index+1} / 20</span></div><article className="rounded-3xl bg-white p-5 shadow-card"><div className="flex gap-2"><span className="rounded-full bg-teal-50 px-2 py-1 text-[11px] font-bold text-teal-700">{q.area}</span><span className="rounded-full bg-stone-100 px-2 py-1 text-[11px] font-bold">{q.type}</span></div><h3 className="mt-4 text-lg font-bold leading-relaxed">{q.question}</h3><div className="mt-5 space-y-2">{q.choices.map((c,i)=><button key={c} onClick={()=>!answered&&setPicked(i)} className={`w-full rounded-2xl border p-4 text-left text-sm font-medium transition ${picked===i?'border-navy bg-blue-50 ring-1 ring-navy':answered&&i===q.answer?'border-emerald-500 bg-emerald-50':'border-stone-200 bg-white'}`}><b className="mr-3 text-teal-700">{String.fromCharCode(65+i)}</b>{c}</button>)}</div>
 {!answered?<><p className="mt-5 text-xs font-bold text-stone-500">얼마나 확신하나요?</p><div className="mt-2 grid grid-cols-3 gap-2">{(Object.keys(labels) as Confidence[]).map(c=><button onClick={()=>setConfidence(c)} key={c} className={`rounded-xl py-2 text-xs font-bold ${confidence===c?'bg-navy text-white':'bg-stone-100 text-stone-500'}`}>{labels[c]}</button>)}</div><button disabled={picked===undefined} onClick={()=>setAnswered(true)} className="mt-4 w-full rounded-2xl bg-navy py-4 font-bold text-white disabled:bg-stone-300">정답 확인</button></>:<div className="mt-5 rounded-2xl bg-teal-50 p-4"><p className={`font-black ${picked===q.answer?'text-teal-700':'text-coral'}`}>{picked===q.answer?'정답이에요! 잘했어요.':'다음 복습에 다시 만나요.'}</p><p className="mt-2 text-sm leading-6">{q.explanation}</p>{q.stages&&<button onClick={()=>setShowStages(!showStages)} className="mt-3 text-sm font-bold text-teal-700">{showStages?'단계 닫기':'SQL 실행 순서 보기 →'}</button>}{showStages&&<ol className="mt-3 space-y-2 border-l-2 border-mint pl-3">{q.stages.map((s)=><li key={s.label}><b className="text-xs">{s.label}</b><p className="text-xs text-stone-600">{s.detail}</p></li>)}</ol>}<button onClick={next} className="mt-4 w-full rounded-xl bg-navy py-3 text-sm font-bold text-white">{index===19?'오늘 루틴 완료':'다음 문제'}</button></div>}</article></>}
 {tab==='review'&&<section><h2 className="font-black">복습 큐</h2><div className="mt-3 rounded-3xl bg-white p-5 shadow-card"><p className="text-3xl font-black text-coral">{wrong}문제</p><p className="mt-1 text-sm text-stone-600">틀린 문제는 1일 · 3일 · 7일 뒤 다시 나와요.</p><button className="mt-4 w-full rounded-2xl bg-navy py-3 font-bold text-white" onClick={()=>setTab('today')}>복습 시작하기</button></div></section>}
 {tab==='stats'&&<section><h2 className="font-black">내 점수 흐름</h2><div className="mt-3 rounded-3xl bg-white p-5 shadow-card"><p className="text-xs font-bold text-stone-500">최근 모의고사 기준 예상 점수</p><p className="mt-1 text-4xl font-black text-teal-700">{score}점 <span className="text-base text-stone-400">/ 100</span></p><p className="mt-2 text-sm">목표 60점까지 <b className="text-coral">{Math.max(0,60-score)}점</b> 남았어요.</p><hr className="my-4"/><p className="font-bold">영역별 정답률</p><div className="mt-3 space-y-3 text-sm"><p>데이터 모델링 <b className="float-right">80%</b></p><div className="h-2 rounded bg-stone-100"><i className="block h-full w-4/5 rounded bg-mint"/></div><p>SQL 기본 및 활용 <b className="float-right">45%</b></p><div className="h-2 rounded bg-stone-100"><i className="block h-full w-[45%] rounded bg-coral"/></div></div></div></section>}</section>
 <nav className="safe-bottom fixed bottom-0 left-1/2 flex w-full max-w-md -translate-x-1/2 justify-around border-t border-stone-200 bg-white pt-3 text-xs font-bold">{[['today','✦','오늘'],['review','↻','복습'],['stats','▥','분석']].map(([id,icon,name])=><button key={id} onClick={()=>setTab(id as typeof tab)} className={`flex w-20 flex-col items-center gap-1 pb-2 ${tab===id?'text-teal-700':'text-stone-400'}`}><span className="text-lg">{icon}</span>{name}</button>)}</nav>
 </main>}
